### ISSUE TITLE
Enable PAT authentication for CLI

### ISSUE THREAD

**Issue by miha42-github** [mediumroast/mediumroast_js#110]
# Introduction

The present authentication method uses browser based device flow and works well, but every 8 hours the user must authenticate using a browser.  The focus of this work is to make use of a GitHub Personal Access Token (PAT) to smooth out authentication.

# Thinking

After reviewing the code this the approach that will be taken to ensure proper configuration and usage of `PAT` or `DeviceFlow`.  Implementation will span all of the CLIs including setup; further as much as possible the changes should be subtle so that not much will be required on the client/CLI side.

## PAT Required permissions

The following permissions are needed for all repositories in a given organization if the goal is to use a PAT.

### Repositories

- Actions: read/write
- Administration: read/write
- Contents: read/write
- Metadata: read
- Pull requests: read/write
- Workflows: read/write

### Organization

- No permissions required

## CLI Client

1. For setup need to ensure that we pass in the authType based upon the prompt from the user
    1. If the prompt is PAT, we need a secondary prompt to obtain the PAT
    2. If we obtain the PAT we need to save that to the config file, but that can come later on in the code
2. For other CLIs prototype mrcli-company and then reflect what changes need to occur here

## GitHubAuth Constructor

Improvements to the constructor are needed to support the inclusion of `verifyAccessToken`.  That's because `verifyAccessToken` will require the ability to check in on the configuration file, update the configuration file, and then write to the file.  

1. Inputs to include env, the constructed `Envrionmentals` module, and the configuration file full path
2. Save these new inputs into the constructed module.

## verifyAccessToken

This will be the main entry point into the module and we will need to think about what's needed for setup.  So it will have to do most of the heavy lifting required to detect authorization type, check token validity, and if possible obtain a new token.  It should be noted that a manual process is required for now to obtain a new `PAT`.  Therefore if the validity check fails for PAT there should be a return that informs the caller this is the case.  It is then up to the caller to determine and execute next steps.  The common flow of the method follows:

  1. Verify that there is a GitHub section and if not then we should return to the caller a false response
  2. Obtain the token from the config file, if it exists
  3. Obtain the authType from the config file, if it exists
  4.  Verify if the token is valid, and if valid return to the caller
      1. If the token is not valid and it is PAT return to the caller and error message stating they need to refresh
      2. If the token is not valid and it is a deviceFlow obtain the token through device flow

General things to consider:
- Returns should include an object containing the token, authType and so on.  This implies all callers will need to adjust to this new structure.
- When the PAT is invalid prompt the user to obtain a new one and update the field in the configuration file.

# Work items

- [x] setup CLI - must include a prompt for authType
- [x] setup CLI - if authType is PAT we will need to prompt the user for the PAT
- [x] setup CLI - add authType to the GitHub settings defaults
- [x] src/api/authorize.js - update getAccessToken to getAccessTokenDeviceFlow
- [x] src/api/authorize.js - change return to include the authType in an Object
- [x] src/api/authorize.js - verify the output for checkTokenExpiration
- [x] verifyAccessToken  - move to src/api/authorize.js
- [x] verifyAccessToken - must have switching logic depending upon authType
- [x] If the token is valid return it to the caller for both deviceFlow and PAT
- [x] Check for token validity with new logic for PAT and return error with instructions if invalid
- [x] Bonus: add prompt for user to choose env.DEFAULT.theme
- [x] Update company CLI
- [x] Update interaction CLI
- [x] Update storage CLI
- [x] Update user CLI
- [x] Update action CLI

# Tests to verify full function

The following tests are considered to verify the full function of this change.

## Setup

The initial set of security permissions for PATs used are captured in the following screenshot. 

![Image](https://github.com/user-attachments/assets/d3db11a3-6062-4b2c-bafe-c8992bca038d)

- [x] Run setup without a PAT to full completion to initially create a repo
- [x] Run setup with an invalid PAT to error, record the error handling behavior
- [x] Run setup with a valid PAT to full completion to initially create a repo this will check if the PAT has the right permissions

After the initial creation of a repo is done with the above scenarios perform the following tests.

- [x] Run setup without removing the config file with a valid PAT
- [x] Run setup without removing the config file with an invalid PAT
- [x] Run setup without removing the config file with a valid deviceFlow
- [x] Run setup without removing the config file with an invalid deviceFlow
- [x] Remove the config file and rerun setup with a valid PAT
- [x] Remove the config file and rerun setup with an invalid PAT
- [x] Remove the config file and rerun setup with a valid deviceFlow
- [x] Remove the config file and rerun setup with an invalid deviceFlow

The final one appears to hang and if you try to enter in the divice code to obtain the token it will error out.  Therefore, it is important to create some documentation which guides to user to the right path.  This path should be to delete `config.ini` and start again.  We will consider in a future release to work through this and make recovery more elegant.

### Progress

- Removal of `config.ini` at the initial run results in a runtime error stating that the file doesn't exist and setup will not run. The failure is in the authentication constructor, will need to put in a check to see if the file exists and if not then we will need to handle things appropriately.
    - In the constructor reading the config file needs to be more nuanced choices are:
        - ~~try/catch for reading the config file~~
        - **pass in a setting to state that the config doesn't exist** we'll do this one since setup already checks to see if the config file is present or not.
    - Add a check in the constructor for `config.ini`, if there load it, if not then the setting is `null`
    - In `verifyAccessToken` check to see if both the config and switch for the config not existing, we will proceed from there.
- It appears as if the PAT doesn't yet have the right permissions for completely merging to main.

## Company, Interaction, Storage, Action, User

- [x] Run getAll for company
- [x] Create an interaction
- [x] Update an interaction
- [x] Delete an interaction
- [x] Create a company
- [x] Update a company
- [x] Delete a company
- [x] Run getAll for storage
- [x] Run getAll for actions
- [x] Run getAll for users

### Progress

- An initial run of obtaining all of the company objects failed with missing `clientId` in the env object, investigating. Investigation showed that the remedy was to check to see if the configuration file exists and if so then we will define `clientId` one way if not then another.

**Comment by miha42-github** [comment]
Minus setup the other CLIs are updated and light testing has occurred to verify functionality.

**Comment by miha42-github** [comment]
PAT is working across all CLIs next step is to test installation via a new repo with the setup script so we can get to a state of good.

**Comment by miha42-github** [comment]
Implementation and quality checks complete, ready for release
