### ISSUE TITLE
mediumroast_js: Complete CLI documentation

### ISSUE THREAD

**Issue by miha42-github** [mediumroast/mediumroast_js#84]
# Introduction
Create documentation for the CLI that shows how to use the CLI for users.  If possible the documentation may also touch on they why behind this open source release.

# Tasks

- [x] Create/update cli/Company.md
- [x] Create/update cli/Interaction.md
- [x] Create/update cli/Setup.md
- [x] Create/update cli/README.md

# Implementation notes
- Major functions should be tested and the process documented in the markdown files to show the operations of the CLI. In general there should be some theory talk for the CLI as it relates to building a corpus for requirements analysis, competitive analysis, and so on.

**Comment by miha42-github** [comment]
Completed
